# /apps/blog.silarhi.fr/docker-compose.yml
version: '3'

services:
  db:
    image: mariadb:10.1.26 
    ports:
      - "3306:3306"
  app:
    image: ghost:4-alpine
    container_name: jrcan
    build: .
    networks:
        - web
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jrcan.rule=Host(`jrcan.dev.netlib.re`)"
        - "traefik.http.routers.jrcan.entrypoints=websecure"
    restart: always

volumes:
  content:

networks:
  web:
    external: true
