version: "3.1"

services:

  nginx: 
    networks:
      - lan
      - web
    build:
      context: .
      dockerfile: nginx.Dockerfile
    #ports:
     # - 80:8080

    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.jrcandev.netlib.re`)"
        - "traefik.http.routers.${NAME}.entrypoints=websecure"
        - "traefik.http.routers.${NAME}.tls.certresolver=lets-encrypt"
    restart: always

  node:
    depends_on:
      - db
    networks:
      - lan
    build:
      context: .
      dockerfile: node.Dockerfile

    restart: always

  db:
    image: postgres:latest
    
    networks:
      - lan
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    expose:
      - 5432

    restart: always



networks:
  web:
    external: true
  lan:
    internal: true