# /apps/blog.silarhi.fr/docker-compose.yml
version: '3'

services:
  app:
    image: ghost:4-alpine
    container_name: drawingtogether
    build: .
    networks:
        - web
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.drawingtogether.rule=Host(`drawingtogether.jrcandev.netlib.re`)"
        - "traefik.http.routers.drawingtogether.entrypoints=websecure"
        - "traefik.http.routers.drawingtogether.tls.certresolver=lets-encrypt"
    restart: always

volumes:
  content:

networks:
  web:
    external: true
