# /apps/blog.silarhi.fr/docker-compose.yml
version: '3'

services:
  db:
    image: mariadb:10.1.26 
    container_name: sqlwp
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLROOT}
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: ${MYSQLDB}
      labels:
        traefik.enable: false  
  app:
    image: ghost:4-alpine
    container_name: jrcan
    build: .
    networks:
        - web
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jrcan.rule=Host(`jrcan.dev.netlib.re`)"
        - "traefik.http.routers.jrcan.entrypoints=websecure"
    restart: always

volumes:
  content:

networks:
  web:
    external: true
